-- Static PL/SQL 의 파라미터 사용방법
DECLARE
    V_BIRTH CST_INFO.BIRTH%TYPE;
    P_CST_ID CST_INFO.CST_ID%TYPE := 'C001';
BEGIN
    SELECT BIRTH
    INTO V_BIRTH
    FROM CST_INFO
    WHERE CST_ID = P_CST_ID;
    DBMS_OUTPUT.PUT_LINE('V_BIRTH: ' || V_BIRTH);
END;