-- Dynamic PL/SQL의 파라미터 사용 방법
DECLARE
    V_BIRTH CST_INFO.BIRTH%TYPE;
    P_CST_ID CST_INFO.CST_ID%TYPE := 'C001';
    V_QRY VARCHAR2(10000);
BEGIN
    V_QRY := 'SELECT BIRTH FROM CST_INFO WHERE CST_ID = :val';
    EXECUTE IMMEDIATE
    V_QRY
    INTO V_BIRTH
    USING P_CST_ID
    ;
    DBMS_OUTPUT.PUT_LINE('V_BIRTH: '||V_BIRTH);
END;
